[package]
edition = "2024"
name = "interactive-worktree"
version = "0.1.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
console = "0.15"
inquire = "0.7"

[profile.release]
codegen-units = 1
lto = true
strip = true
